[phases.setup]
nixPkgs = ["python3", "nodejs", "nodePackages.npm"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "source /opt/venv/bin/activate && pip install --upgrade pip",
  "source /opt/venv/bin/activate && pip install -r requirements_railway.txt",
  "source /opt/venv/bin/activate && playwright install chromium"
]

[phases.build]
cmds = [
  "source /opt/venv/bin/activate && python --version",
  "source /opt/venv/bin/activate && pip list",
  "source /opt/venv/bin/activate && playwright --version",
  "source /opt/venv/bin/activate && python -c 'print(\"Build completed successfully!\")'"
]

[start]
cmd = "source /opt/venv/bin/activate && python scheduler/run_campaign.py" 