[phases.setup]
nixPkgs = ["python3", "python3Packages.venv", "nodejs", "nodePackages.npm"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "source /opt/venv/bin/activate && pip install -r requirements_railway.txt",
  "source /opt/venv/bin/activate && playwright install chromium"
]

[phases.build]
cmds = [
  "source /opt/venv/bin/activate && python -c 'import sys; print(f\"Python {sys.version}\")'",
  "source /opt/venv/bin/activate && python -c 'import requests; print(\"Requests installed\")'",
  "source /opt/venv/bin/activate && python -c 'import bs4; print(\"BeautifulSoup installed\")'",
  "source /opt/venv/bin/activate && python -c 'import pandas; print(\"Pandas installed\")'",
  "source /opt/venv/bin/activate && python -c 'import openpyxl; print(\"OpenPyXL installed\")'",
  "source /opt/venv/bin/activate && python -c 'import selenium; print(\"Selenium installed\")'",
  "source /opt/venv/bin/activate && python -c 'import fake_useragent; print(\"FakeUserAgent installed\")'",
  "source /opt/venv/bin/activate && python -c 'import playwright; print(\"Playwright installed\")'",
  "source /opt/venv/bin/activate && python -c 'import schedule; print(\"Schedule installed\")'",
  "source /opt/venv/bin/activate && python -c 'import psutil; print(\"Psutil installed\")'",
  "source /opt/venv/bin/activate && python -c 'import groq; print(\"Groq SDK installed\")'",
  "source /opt/venv/bin/activate && python -c 'import sendgrid; print(\"SendGrid installed\")'",
  "source /opt/venv/bin/activate && python -c 'import urllib3; print(\"Urllib3 installed\")'",
  "source /opt/venv/bin/activate && python -c 'import lxml; print(\"LXML installed\")'",
  "source /opt/venv/bin/activate && playwright --version",
  "source /opt/venv/bin/activate && python -c 'print(\"All dependencies installed successfully!\")'"
]

[start]
cmd = "source /opt/venv/bin/activate && python scheduler/daily_campaign.py" 