[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "nodejs", "nodePackages.npm"]

[phases.install]
cmds = [
  "pip install -r requirements_railway.txt",
  "playwright install chromium"
]

[phases.build]
cmds = [
  "python -c 'import sys; print(f\"Python {sys.version}\")'",
  "python -c 'import requests; print(\"Requests installed\")'",
  "python -c 'import bs4; print(\"BeautifulSoup installed\")'",
  "python -c 'import pandas; print(\"Pandas installed\")'",
  "python -c 'import schedule; print(\"Schedule installed\")'",
  "python -c 'import psutil; print(\"Psutil installed\")'",
  "python -c 'import playwright; print(\"Playwright installed\")'",
  "playwright --version",
  "python -c 'print(\"Build completed successfully\")'"
]

[start]
cmd = "python scheduler/daily_campaign.py" 