[phases.setup]
nixPkgs = ["python3", "python3-pip"]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python -c 'import sys; print(f\"Python {sys.version}\")'",
  "python -c 'print(\"Build completed successfully\")'"
]

[start]
cmd = "python scheduler/daily_campaign.py" 